name: build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  statuses: write

jobs:
  esphome_compile:
    name: run esphome compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: create dummy secrets.yaml file
        run: touch ./secrets.yaml && cp ./ac.example.secrets.yaml ./secrets.yaml
      
      # TODO: esphome container runs as root
      # gh-issue: https://github.com/esphome/issues/issues/3558
      # - name: create esphome cache key
      #   id: create_cache_key
      #   run: |
      #     source ./.esphomeversion

      #     esphomeVersion="${ESPHOME_VERSION}"
      #     esphomeConfigHash="$(bash ./config-hash.sh)"

      #     echo "cache_key=${RUNNER_OS}-esphome-${esphomeVersion}-config-${esphomeConfigHash}"
      #     echo "cache_key=${RUNNER_OS}-esphome-${esphomeVersion}-config-${esphomeConfigHash}" >> "${GITHUB_OUTPUT}"

      # - name: initialize esphome cache
      #   uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5.1.0
      #   with:
      #     path: ./.esphome
      #     key: ${{ steps.create_cache_key.outputs.cache_key }}

      - name: compile component        
        id: compile_component_step
        run: bash ./build.sh

      - name: set commit status
        if: ${{ always() && contains(fromJSON('["success", "failure"]'), steps.compile_component_step.conclusion) }}
        env:
          GH_TOKEN: ${{ github.token }}
          COMPILE_STATE: ${{ steps.compile_component_step.conclusion }}
        run: |
           source ./.esphomeversion
            
           gh api "/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}" \
            -H "Accept: application/vnd.github+json" \
            --method POST \
            -f state="${COMPILE_STATE}" \
            -f context="build/esphomeversion" \
            -f description="ESPHome v${ESPHOME_VERSION}" \
            -f target_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"      
        
